services:
  notification-service:
    build: .
    env_file:
      - ../.env
    image: vplmqa/notification
    ports: ["8085:8085"]
    depends_on:
      config-service: { condition: service_healthy }
      postgres: { condition: service_healthy }
      kafka: { condition: service_healthy }



