ALTER TABLE figma_components
    ADD COLUMN IF NOT EXISTS figma_node_id VARCHAR(255),
    ADD COLUMN IF NOT EXISTS figma_node_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS figma_node_type VARCHAR(100),
    ADD COLUMN IF NOT EXISTS position_x DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS position_y DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS node_width DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS node_height DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS source_file_key VARCHAR(255),
    ADD COLUMN IF NOT EXISTS source_file_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS raw_json TEXT,
    ADD COLUMN IF NOT EXISTS imported_at TIMESTAMP;