ALTER TABLE project_settings
    ADD COLUMN IF NOT EXISTS email_notifications BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS slack_notifications BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS notify_on_failure BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS weekly_summary_reports BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS run_tests_on_deploy BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS ai_insights BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS screenshot_comparison BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS test_timeout_seconds INTEGER NOT NULL DEFAULT 30,
    ADD COLUMN IF NOT EXISTS schedule_type VARCHAR(32) NOT NULL DEFAULT 'daily',
    ADD COLUMN IF NOT EXISTS schedule_interval_hours INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS schedule_daily_time VARCHAR(8) NOT NULL DEFAULT '06:00';
